matrix:
  include:
    - os: linux
      language: 
      before_script:
        - echo no | android create avd --force -n test -t android-23 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install node
    - os: osx
      language: node_js
      node_js: "6"
      osx_image: xcode8.3

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

install:
    - wget https://github.com/zbranzov/travisTest.git
    - cd seed-tests
    - npm i

script:
    - npm run test